export const pokemone = [
    {
        
        id:1,
        nombre: "Bulbasaur",
        precio: 300,
        image: "https://www.pngmart.com/files/11/Pokemon-Bulbasaur-PNG-HD.png",
        clase: "https://cdn.pixabay.com/photo/2018/05/20/01/41/pokemon-3414810_960_720.png",
        tipo: "planta"
        },

        {
            id:2,
            nombre: "Squirtle",
            precio: 300,
            image: "https://www.pngmart.com/files/22/Squirtle-Pokemon-PNG-HD-Isolated.png",
            clase: "https://cdn.pixabay.com/photo/2018/05/21/13/06/pokemon-3418257_1280.png",
            tipo: "agua"
        },
        
        {
            id:3,
            nombre: "Charmander",
            precio: 300,
            image : "https://www.pngmart.com/files/13/Charmander-PNG-Clipart.png",
            clase : "https://cdn.pixabay.com/photo/2018/05/20/01/40/pokemon-3414807_1280.png",
             tipo: "fuego"
        },
        
        {
            id:4,
            nombre: "Pikachu",
            precio: 400,
            image : "http://assets.stickpng.com/images/580b57fcd9996e24bc43c325.png",
            clase : "https://cdn.pixabay.com/photo/2018/05/18/15/43/pokemon-3411389_960_720.png",
            tipo: "electricidad"
        },
        
        





    
]